---
title: "Homework8"
output:
  pdf_document: default
  html_document: default
date: "2024-04-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1\

```{r 1a}
set.seed(1)
x <- 1:100
epsilon <- rnorm(100,0,6) 
Y_sample <- 1 + 2*x + epsilon
plot(x,Y_sample,main = "Scatterplot and Regression Line",xlab = "X", ylab = "Sample", col = "lightblue")
abline(lm(Y_sample ~ x), col = "blue")
```

Two Sided Significance Test: \

Step 1: Model for data, Y~N(B0 + B1x, $\sigma^2$) \

Step 2: \
Null Hypothesis(H0): B1 = 2 \
Alternate Hypothesis(H1): B1 $\ne$ 2 \

Step 3: Test statistic: t statistic \

Step 4: 
```{r 1b}
B1 <- coef(lm(Y_sample ~ x))[2] 
B1
SE <- summary(lm(Y_sample ~ x))$coefficients[2, 2] 
SE
t <- (1.997294-2)/SE 
t
```
Step 5: \
Calculating the p-value under H0,

```{r 1c}
p <- pt(abs(t), df = 98, lower.tail = FALSE) * 2 
p
```

Step 6: \
Significance level, $\alpha$ = 0.05 \

Step 7: \
p-value = 0.8856209 > $\alpha$ \
Hence, fail to reject the null hypothesis of B1 = 2

## Question 2 \

```{r 2a}
price <- c(300000, 250000, 400000, 550000, 317000, 389000, 425000, 289000, 389000)
bedrooms <- c(3,3,4,5,4,3,6,3,4)
plot(bedrooms,price,main="Price vs Number of Bedrooms",xlab = "Number
of bedrooms", ylab = "Price", col = "orange") 
abline(lm(price ~ bedrooms), col = "purple")

new_data <- data.frame(bedrooms = 2:8)
pred <- predict(lm(price ~ bedrooms), newdata = new_data, 
        interval = c("confidence"), level = 0.95)
pred_df <- data.frame(new_data, pred)
pred_df
```


## Question 3

```{r 3a}
library(UsingR)
data(deflection)
lm_model <- lm(Deflection ~ Load, data = deflection)
plot(deflection$Load, deflection$Deflection, 
     main = "Deflection vs Load",
     xlab = "Load", ylab = "Deflection", col = "red")
abline(lm_model, col = "pink")

confint(lm_model, level = 0.95)
```

